'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System
Namespace Solution28.Web


	Partial Public Class DefaultVerticalTemplateContent1

		''' <summary>
		''' GE control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected GE As Global.DevExpress.Web.ASPxGlobalEvents.ASPxGlobalEvents

		''' <summary>
		''' LogoLink control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected LogoLink As Global.System.Web.UI.WebControls.HyperLink

		''' <summary>
		''' TIC control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected TIC As Global.DevExpress.ExpressApp.Web.Controls.ThemedImageControl

		''' <summary>
		''' UPSAC control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected UPSAC As Global.DevExpress.ExpressApp.Web.Templates.XafUpdatePanel

		''' <summary>
		''' SAC control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected SAC As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.MyActionContainerHolder

		''' <summary>
		''' UPSHC control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected UPSHC As Global.DevExpress.ExpressApp.Web.Templates.XafUpdatePanel

		''' <summary>
		''' SHC control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected SHC As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.MyActionContainerHolder

		''' <summary>
		''' UPNC control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected UPNC As Global.DevExpress.ExpressApp.Web.Templates.XafUpdatePanel

		''' <summary>
		''' NC control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected NC As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.NavigationActionContainer

		''' <summary>
		''' UPTP control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected UPTP As Global.DevExpress.ExpressApp.Web.Templates.XafUpdatePanel

		''' <summary>
		''' TP control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected TP As Global.System.Web.UI.HtmlControls.HtmlGenericControl

		''' <summary>
		''' TRP control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected TRP As Global.DevExpress.Web.ASPxRoundPanel.ASPxRoundPanel

		''' <summary>
		''' PanelContent1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected PanelContent1 As Global.DevExpress.Web.ASPxPanel.PanelContent

		''' <summary>
		''' VTC control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected VTC As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.MyActionContainerHolder

		''' <summary>
		''' DAC control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected DAC As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.MyActionContainerHolder

		''' <summary>
		''' UPTB control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected UPTB As Global.DevExpress.ExpressApp.Web.Templates.XafUpdatePanel

		''' <summary>
		''' TB control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected TB As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.MyActionContainerHolder

		''' <summary>
		''' UPVH control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected UPVH As Global.DevExpress.ExpressApp.Web.Templates.XafUpdatePanel

		''' <summary>
		''' VIC control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected VIC As Global.DevExpress.ExpressApp.Web.Controls.ViewImageControl

		''' <summary>
		''' VCC control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected VCC As Global.DevExpress.ExpressApp.Web.Controls.ViewCaptionControl

		''' <summary>
		''' VHC control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected VHC As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.NavigationHistoryActionContainer

		''' <summary>
		''' RNC control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected RNC As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.MyActionContainerHolder

		''' <summary>
		''' UPEMA control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected UPEMA As Global.DevExpress.ExpressApp.Web.Templates.XafUpdatePanel

		''' <summary>
		''' EMA control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected EMA As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.MyActionContainerHolder

		''' <summary>
		''' UPEI control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected UPEI As Global.DevExpress.ExpressApp.Web.Templates.XafUpdatePanel

		''' <summary>
		''' ErrorInfo control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ErrorInfo As Global.DevExpress.ExpressApp.Web.Templates.Controls.ErrorInfoControl

		''' <summary>
		''' UPVSC control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected UPVSC As Global.DevExpress.ExpressApp.Web.Templates.XafUpdatePanel

		''' <summary>
		''' VSC control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected VSC As Global.DevExpress.ExpressApp.Web.Controls.ViewSiteControl

		''' <summary>
		''' EditModeActions2 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected EditModeActions2 As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.MyActionContainerHolder

		''' <summary>
		''' UPQC control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected UPQC As Global.DevExpress.ExpressApp.Web.Templates.XafUpdatePanel

		''' <summary>
		''' QC control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected QC As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.QuickAccessNavigationActionContainer

		''' <summary>
		''' UPIMP control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected UPIMP As Global.DevExpress.ExpressApp.Web.Templates.XafUpdatePanel

		''' <summary>
		''' InfoMessagesPanel control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected InfoMessagesPanel As Global.System.Web.UI.WebControls.Literal

		''' <summary>
		''' AIC control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected AIC As Global.DevExpress.ExpressApp.Web.Controls.AboutInfoControl
	End Class
End Namespace
